export const POST_ACTIONS = {
    SET_FIELDS: 'SET_FIELDS',
    SET_TAGS: 'SET_TAGS',
    SET_VISIBILITY: 'SET_VISIBILITY',
    SET_CONTENT: 'SET_CONTENT',
    SET_TITLE: 'SET_TITLE',
    SET_CATEGORY: 'SET_CATEGORY',
    RESET_FORM: 'RESET_FORM',
};
